%%{ init: { 'theme': 'dark', 'flowchart': { 'curve': 'basis' } } }%%
graph LR

  subgraph GeneralsMD
    _euler_unpack_order["_euler_unpack_order"]
    _penter["_penter"]
    _pleave["_pleave"]
    _PivotClass__["~PivotClass()"]
    _PolygonInfoClass["~PolygonInfoClass"]
    AdaptiveDeltaMotionChannelClass__Get_QuatVector["AdaptiveDeltaMotionChannelClass::Get_QuatVector"]
    AdaptiveDeltaMotionChannelClass__Get_Vector["AdaptiveDeltaMotionChannelClass::Get_Vector"]
    AdaptiveDeltaMotionChannelClass__getframe["AdaptiveDeltaMotionChannelClass::getframe"]
    Add_Delayed_Release_Object["Add_Delayed_Release_Object"]
    Add_Files["Add_Files"]
    Add_Object_Internal["Add_Object_Internal"]
    Add_Quad["Add_Quad"]
    Add_Ref["Add_Ref"]
    Add_To_Report["Add_To_Report"]
    AddResultFunction["AddResultFunction"]
    Allocate_Miles_Handle["Allocate_Miles_Handle"]
    Anim_Update["Anim_Update"]
    Are_Mappers_Time_Variant["Are_Mappers_Time_Variant"]
    AUD_service_device["AUD_service_device"]
    AUD_ThreadCreate["AUD_ThreadCreate"]
    AUD_ThreadDestroy["AUD_ThreadDestroy"]
    AudioAttribsInit["AudioAttribsInit"]
    AudioCallbackListClass_T___Add_Callback["AudioCallbackListClass<T>::Add_Callback"]
    AudioCallbackListClass_T___Remove_Callback["AudioCallbackListClass<T>::Remove_Callback"]
    audioChannelCreate["audioChannelCreate"]
    audioChannelRecalcAttribs["audioChannelRecalcAttribs"]
    AudioChannelSetSample["AudioChannelSetSample"]
    AudioChannelStart["AudioChannelStart"]
    AudioFormatReadWaveFile["AudioFormatReadWaveFile"]
    audioOpen["audioOpen"]
    audioOpenChannel["audioOpenChannel"]
    audioStart["audioStart"]
    AudioStreamerDump["AudioStreamerDump"]
    AudioStreamerInit["AudioStreamerInit"]
    AudioStreamerStart["AudioStreamerStart"]
    Base_Update["Base_Update"]
    Base64_Decode["Base64_Decode"]
    Base64_Encode["Base64_Encode"]
    Base64Pipe__Flush["Base64Pipe::Flush"]
    Base64Pipe__Put["Base64Pipe::Put"]
    Bias["Bias"]
    Bit_Blit["Bit_Blit"]
    Bit_Blit__overload_1_["Bit_Blit (overload 1)"]
    Bitmap_Assert["Bitmap_Assert"]
    Bitmap2DObjClass__copy_constructor_["Bitmap2DObjClass (copy constructor)"]
    Bitmap2DObjClass__filename_constructor_["Bitmap2DObjClass (filename constructor)"]
    Bitmap2DObjClass__texture_constructor_["Bitmap2DObjClass (texture constructor)"]
    Blend_Update["Blend_Update"]
    Blit_Block["Blit_Block"]
    Blit_Clip["Blit_Clip"]
    Blitter__Blit["Blitter::Blit"]
    Blitter_From_Flags["Blitter_From_Flags"]
    BlowStraw__Get["BlowStraw::Get"]
    BooleanVectorClass__operator__["BooleanVectorClass::operator[]"]
    BoxRenderObjClass__Init["BoxRenderObjClass::Init"]
    BoxRenderObjClass__render_box["BoxRenderObjClass::render_box"]
    BTREE_about["BTREE_about"]
    Buff_Get["Buff_Get"]
    Buffer__Buffer_long_size_["Buffer::Buffer(long size)"]
    Buffer__Buffer_void_buffer__long_size_["Buffer::Buffer(void buffer, long size)"]
    BufferPipe__Put["BufferPipe::Put"]
    BufferStraw__Get["BufferStraw::Get"]
    Build_AABTree["Build_AABTree"]
    Build_Mesh["Build_Mesh"]
    Build_Sentence["Build_Sentence"]
    Build_Texture["Build_Texture"]
    Build_Textures["Build_Textures"]
    Build_Tree["Build_Tree"]
    BWRenderClass__Render_Triangle_Strip["BWRenderClass::Render_Triangle_Strip"]
    BWRenderClass__Render_Triangles["BWRenderClass::Render_Triangles"]
    Cache["Cache"]
    CacheStraw__Get["CacheStraw::Get"]
    calcThat["calcThat"]
    calcThis["calcThis"]
    Callback_Process_Mouse["Callback_Process_Mouse"]
    Cast_AABox["Cast_AABox"]
    Cast_AABox_AABoxCollisionTestClass___boxtest_["Cast_AABox(AABoxCollisionTestClass & boxtest)"]
    Cast_Ray["Cast_Ray"]
    Cast_Ray_RayCollisionTestClass___raytest_["Cast_Ray(RayCollisionTestClass & raytest)"]
    Cast_Ray_Recursive["Cast_Ray_Recursive"]
    Cast_Semi_Infinite_Axis_Aligned_Ray_To_Triangle["Cast_Semi_Infinite_Axis_Aligned_Ray_To_Triangle"]
    Cftp__AsyncGetHostByName["Cftp::AsyncGetHostByName"]
    Cftp__ConnectToServer["Cftp::ConnectToServer"]
    Cftp__FileRecoveryPosition["Cftp::FileRecoveryPosition"]
    Check_Depth_Stencil_Support["Check_Depth_Stencil_Support"]
    Check_Driver_Version_Status["Check_Driver_Version_Status"]
    Clear["Clear"]
    Clip_Triangle_To_LineXY["Clip_Triangle_To_LineXY"]
    Close["Close"]
    collect_objects_in_leaf["collect_objects_in_leaf"]
    Collect_Objects_Recursive["Collect_Objects_Recursive"]
    Collide["Collide"]
    CollisionMath__Overlap_Test_PlaneClass__AABoxClass_["CollisionMath::Overlap_Test(PlaneClass, AABoxClass)"]
    Color_to_Vector4["Color_to_Vector4"]
    Combine_A8R8G8B8["Combine_A8R8G8B8"]
    Combine_Colors["Combine_Colors"]
    Combo_Update["Combo_Update"]
    Commit["Commit"]
    Compare_EXE_Version["Compare_EXE_Version"]
    compressData["compressData"]
    Compute_Plane_Score["Compute_Plane_Score"]
    Convert["Convert"]
    Convert_From["Convert_From"]
    Convert_System_Error_To_String["Convert_System_Error_To_String"]
    ConvertGrab_void_BitmapPointer_["ConvertGrab(void BitmapPointer)"]
    Copy_Emitter_Property_Struct["Copy_Emitter_Property_Struct"]
    Copy_Image["Copy_Image"]
    Copy_Image_Generate_Mipmap["Copy_Image_Generate_Mipmap"]
    Copy_Pixel["Copy_Pixel"]
    CRC_Stringi["CRC_Stringi"]
    CRCPipe__Put["CRCPipe::Put"]
    CRCPipe__Result["CRCPipe::Result"]
    CRCStraw__Get["CRCStraw::Get"]
    Create["Create"]
    Create_Delayed_Release_Thread["Create_Delayed_Release_Thread"]
    Create_Mipmap_B8G8R8A8["Create_Mipmap_B8G8R8A8"]
    Create_ShdDefClass_Instance_uint32_class_id_["Create_ShdDefClass_Instance(uint32 class_id)"]
    CriticalSectionClass__Lock__["CriticalSectionClass::Lock()"]
    CriticalSectionClass__Unlock__["CriticalSectionClass::Unlock()"]
    Cull["Cull"]
    Cull_const_Vector3___min__const_Vector3___max_["Cull(const Vector3 & min, const Vector3 & max)"]
    DecalPolyClass__Clip["DecalPolyClass::Clip"]
    DecalSystemClass__Lock_Decal_Generator["DecalSystemClass::Lock_Decal_Generator"]
    decompressData["decompressData"]
    Decrypt["Decrypt"]
    Define_FVF_MeshModelClass__bool_["Define_FVF(MeshModelClass, bool)"]
    Define_FVF_ShdSubMeshClass__bool_["Define_FVF(ShdSubMeshClass, bool)"]
    Delayed_Release_Thread_Proc["Delayed_Release_Thread_Proc"]
    Do_Mappers_Need_Normals["Do_Mappers_Need_Normals"]
    Dot_Product["Dot_Product"]
    Draw_Sentence["Draw_Sentence"]
    Draw_Shape["Draw_Shape"]
    Draw_Text["Draw_Text"]
    Draw_Triangles["Draw_Triangles"]
    DynamicAudioSaveLoadClass__Load["DynamicAudioSaveLoadClass::Load"]
    DynamicAudioSaveLoadClass__Save["DynamicAudioSaveLoadClass::Save"]
    DynamicVectorClass_T___Add["DynamicVectorClass<T>::Add"]
    DynamicVectorClass_T___Delete["DynamicVectorClass<T>::Delete"]
    EditableClass__Lock_Parameter["EditableClass::Lock_Parameter"]
    Encrypt["Encrypt"]
    End["End"]
    End_Delayed_Release_Thread["End_Delayed_Release_Thread"]
    End_Sample["End_Sample"]
    EulerAnglesClass__EulerAnglesClass__Matrix3D__int_["EulerAnglesClass::EulerAnglesClass (Matrix3D, int)"]
    EulerAnglesClass__From_Matrix["EulerAnglesClass::From_Matrix"]
    EulerAnglesClass__To_Matrix["EulerAnglesClass::To_Matrix"]
    eval_overlap_collision["eval_overlap_collision"]
    Evaluate["Evaluate"]
    Execute["Execute"]
    Export["Export"]
    failsafeGetTime["failsafeGetTime"]
    FastAllocatorGeneral__Alloc["FastAllocatorGeneral::Alloc"]
    FastAllocatorGeneral__FastAllocatorGeneral["FastAllocatorGeneral::FastAllocatorGeneral"]
    FastAllocatorGeneral__Get_Allocator["FastAllocatorGeneral::Get_Allocator"]
    FileClass__Printf_char_buffer__int_bufferSize__char_str______["FileClass::Printf(char buffer, int bufferSize, char str, ...)"]
    FileClass__Printf_char_str______["FileClass::Printf(char str, ...)"]
    FileClass__Printf_Indented_unsigned_depth__char_str______["FileClass::Printf_Indented(unsigned depth, char str, ...)"]
    Fill_Buffer_From_System["Fill_Buffer_From_System"]
    Find_Factory_const_char_name_["Find_Factory(const char name)"]
    Find_Tangents["Find_Tangents"]
    fixed__As_ASCII__["fixed::As_ASCII()"]
    fixed__fixed_char_const__ascii_["fixed::fixed(char const  ascii)"]
    fixed__To_ASCII_char__buffer__int_maxlen_["fixed::To_ASCII(char  buffer, int maxlen)"]
    Flush["Flush"]
    Flush_Delayed_Release_Objects["Flush_Delayed_Release_Objects"]
    Format_Args["Format_Args"]
    Free["Free"]
    Free_Miles_Handle["Free_Miles_Handle"]
    From_Buffer["From_Buffer"]
    Generate_APT["Generate_APT"]
    Get_4x4_Block["Get_4x4_Block"]
    Get_Bytes_Per_Pixel["Get_Bytes_Per_Pixel"]
    Get_Deformed_Vertices_Vector3__Vector3__const_HTreeClass_["Get_Deformed_Vertices(Vector3, Vector3, const HTreeClass)"]
    get_far_extent["get_far_extent"]
    Get_File_Id_String["Get_File_Id_String"]
    Get_First_uint32_superclass_id_["Get_First(uint32 superclass_id)"]
    Get_Last_System_Error["Get_Last_System_Error"]
    Get_Mapper["Get_Mapper"]
    Get_Material["Get_Material"]
    Get_Next_DefinitionFactoryClass_curr_factory__uint32_superclass_id_["Get_Next(DefinitionFactoryClass curr_factory, uint32 superclass_id)"]
    Get_Pixel["Get_Pixel"]
    Get_Point_char_const__section__char_const__entry__TPoint2D_int__const___defvalue__const["Get_Point(char const  section, char const  entry, TPoint2D<int> const & defvalue) const"]
    Get_Render_Object["Get_Render_Object"]
    Get_Sample_Volume["Get_Sample_Volume"]
    Get_String["Get_String"]
    Get_String_char_const__section__char_const__entry__char_const__defvalue__char__buffer__int_buflen__const["Get_String(char const  section, char const  entry, char const  defvalue, char  buffer, int buflen) const"]
    Get_Texture["Get_Texture"]
    GetClockCyclesFast["GetClockCyclesFast"]
    getCompressionType["getCompressionType"]
    GetFileCreationTime["GetFileCreationTime"]
    getMaxCompressedSize["getMaxCompressedSize"]
    getMipmapData_MultiRequest__m_["getMipmapData(MultiRequest& m)"]
    GetVersionInfo["GetVersionInfo"]
    getVertexBuffer["getVertexBuffer"]
    Grab_void_BitmapPointer_["Grab(void BitmapPointer)"]
    GrabAVI_void_BitmapPointer_["GrabAVI(void BitmapPointer)"]
    GridCullSystemClass__Collect_Objects["GridCullSystemClass::Collect_Objects"]
    GridCullSystemClass__link_object["GridCullSystemClass::link_object"]
    GridCullSystemClass__Re_Partition["GridCullSystemClass::Re_Partition"]
    HAnimComboClass__Normalize_Weights["HAnimComboClass::Normalize_Weights"]
    HashListClass__Add_T_record__unsigned_key_["HashListClass::Add(T record, unsigned key)"]
    HashTableClass__Add["HashTableClass::Add"]
    HashTableClass__Find["HashTableClass::Find"]
    HashTableClass__Hash["HashTableClass::Hash"]
    HashTableClass__Remove["HashTableClass::Remove"]
    HashTableIteratorClass__First["HashTableIteratorClass::First"]
    HashTableIteratorClass__Next["HashTableIteratorClass::Next"]
    HCompressedAnimClass__Load_W3D["HCompressedAnimClass::Load_W3D"]
    Hide_Mouse["Hide_Mouse"]
    highResGetTime["highResGetTime"]
    HModelLoaderClass__Load_W3D["HModelLoaderClass::Load_W3D"]
    HRawAnimClass__Get_Orientation["HRawAnimClass::Get_Orientation"]
    HRawAnimClass__Get_Transform["HRawAnimClass::Get_Transform"]
    HRawAnimClass__Load_W3D["HRawAnimClass::Load_W3D"]
    HTreeClass__Anim_Update["HTreeClass::Anim_Update"]
    HTreeClass__Blend_Update["HTreeClass::Blend_Update"]
    HTreeClass__Combo_Update["HTreeClass::Combo_Update"]
    HTreeClass__Load_W3D["HTreeClass::Load_W3D"]
    HUFF_about["HUFF_about"]
    IDBufferClass__Render_Non_Occluder_Scanline["IDBufferClass::Render_Non_Occluder_Scanline"]
    IDBufferClass__Render_Occluder_Scanline["IDBufferClass::Render_Occluder_Scanline"]
    IDBufferClass__Render_Triangle["IDBufferClass::Render_Triangle"]
    IMA_decode_block["IMA_decode_block"]
    Init["Init"]
    Init_From_Legacy_Mesh_Model_MeshModelClass__int_["Init_From_Legacy_Mesh_Model(MeshModelClass, int)"]
    InitAudioTimer["InitAudioTimer"]
    Initialize["Initialize"]
    Initialize_Miles_Handle["Initialize_Miles_Handle"]
    Insert_To_Sorting_Pool["Insert_To_Sorting_Pool"]
    Insert_Triangles__overload_1_["Insert_Triangles (overload 1)"]
    Insert_Triangles__overload_2_["Insert_Triangles (overload 2)"]
    Insert_VolumeParticle["Insert_VolumeParticle"]
    Install_Materials["Install_Materials"]
    Int__exp_b_mod_c["Int::exp_b_mod_c"]
    Internal_Add__["Internal_Add()"]
    Internal_Remove__["Internal_Remove()"]
    Intersect_Object_Array["Intersect_Object_Array"]
    Intersect_Screen_Point_Layer["Intersect_Screen_Point_Layer"]
    Intersect_Sphere["Intersect_Sphere"]
    Intersection_Test["Intersection_Test"]
    Is_Texture_Valid["Is_Texture_Valid"]
    LaunchWebBrowser["LaunchWebBrowser"]
    LCW_Comp["LCW_Comp"]
    LCW_Uncomp["LCW_Uncomp"]
    LCWPipe__Flush["LCWPipe::Flush"]
    LCWPipe__Put["LCWPipe::Put"]
    LightEnvironmentClass__Calculate_Fill_Light["LightEnvironmentClass::Calculate_Fill_Light"]
    Load["Load"]
    Load_Straw___ffile_["Load(Straw & ffile)"]
    Load_Shader_ChunkLoadClass__cload__ShdDefClass_shddef_["Load_Shader(ChunkLoadClass& cload, ShdDefClass shddef)"]
    Load_Texture["Load_Texture"]
    Load_Variables["Load_Variables"]
    Load_W3D["Load_W3D"]
    Load_W3D_ChunkLoadClass__["Load_W3D(ChunkLoadClass&)"]
    Log["Log"]
    lzo1x_1_compress["lzo1x_1_compress"]
    lzo1x_decompress["lzo1x_decompress"]
    LZOCompressor__Compress["LZOCompressor::Compress"]
    LZOCompressor__Decompress["LZOCompressor::Decompress"]
    LZOPipe__Flush["LZOPipe::Flush"]
    LZOPipe__Put["LZOPipe::Put"]
    main["main"]
    MaterialCollectorClass__Collect_Materials["MaterialCollectorClass::Collect_Materials"]
    MaterialRemapperClass__Remap_Mesh["MaterialRemapperClass::Remap_Mesh"]
    MeshLoaderClass__Load_W3D["MeshLoaderClass::Load_W3D"]
    MeshMatDescClass__Do_Mappers_Need_Normals["MeshMatDescClass::Do_Mappers_Need_Normals"]
    MeshMatDescClass__Install_UV_Array["MeshMatDescClass::Install_UV_Array"]
    MeshMatDescClass__Post_Load_Process["MeshMatDescClass::Post_Load_Process"]
    Message_Handler["Message_Handler"]
    MetalMapManagerClass_INIClass__ini_["MetalMapManagerClass(INIClass &ini)"]
    MixFileFactoryClass__Get_File["MixFileFactoryClass::Get_File"]
    MotionChannelClass__Get_Vector["MotionChannelClass::Get_Vector"]
    MotionChannelClass__Load_W3D["MotionChannelClass::Load_W3D"]
    MS_decode_block["MS_decode_block"]
    MultiFixedPoolDecalSystemClass__Clear_Decal_Slot["MultiFixedPoolDecalSystemClass::Clear_Decal_Slot"]
    MultiFixedPoolDecalSystemClass__find_logical_decal["MultiFixedPoolDecalSystemClass::find_logical_decal"]
    MultiFixedPoolDecalSystemClass__Lock_Decal_Generator["MultiFixedPoolDecalSystemClass::Lock_Decal_Generator"]
    MultiFixedPoolDecalSystemClass__Unlock_Decal_Generator["MultiFixedPoolDecalSystemClass::Unlock_Decal_Generator"]
    MutexClass__Lock_int_time_["MutexClass::Lock(int time)"]
    MutexClass__Unlock__["MutexClass::Unlock()"]
    NormalCone__Get_Coplanar_Normals_const_Vector3___Input__Vector3___Output1__Vector3___Output2_["NormalCone::Get_Coplanar_Normals(const Vector3 & Input, Vector3 & Output1, Vector3 & Output2)"]
    NormalCone__Merge_const_NormalCone___Input_["NormalCone::Merge(const NormalCone & Input)"]
    NormalCone__Merge_const_Vector3___Input_["NormalCone::Merge(const Vector3 & Input)"]
    NormalCone__Smallest_Dot_Product_const_Vector3___Input_["NormalCone::Smallest_Dot_Product(const Vector3 & Input)"]
    Notify_Added_Notify_Removed["Notify_Added/Notify_Removed"]
    NTreeLeafClass_T___Add_Child["NTreeLeafClass<T>::Add_Child"]
    Obfuscate["Obfuscate"]
    ObjectPoolClass__Allocate_Object["ObjectPoolClass::Allocate_Object"]
    ObjectPoolClass__Free_Object["ObjectPoolClass::Free_Object"]
    On_Added_To_Scene["On_Added_To_Scene"]
    On_Event["On_Event"]
    On_Frame_Update["On_Frame_Update"]
    On_Removed_From_Scene["On_Removed_From_Scene"]
    Open["Open"]
    operator___overloads_["operator+ (overloads)"]
    Optimize_Mesh["Optimize_Mesh"]
    Overlap_Test_const_AAPlaneClass____const_LineSegClass___["Overlap_Test(const AAPlaneClass &, const LineSegClass &)"]
    Overlap_Test_const_OBBoxClass____const_LineSegClass___["Overlap_Test(const OBBoxClass &, const LineSegClass &)"]
    Overlap_Test_const_OBBoxClass____const_TriClass___["Overlap_Test(const OBBoxClass &, const TriClass &)"]
    Overlap_Test_const_PlaneClass____const_OBBoxClass___["Overlap_Test(const PlaneClass &, const OBBoxClass &)"]
    Overlap_Test_const_SphereClass____const_AABoxClass___["Overlap_Test(const SphereClass &, const AABoxClass &)"]
    Overlap_Test_const_SphereClass____const_OBBoxClass___["Overlap_Test(const SphereClass &, const OBBoxClass &)"]
    ParticleEmitterDefClass__Load_W3D["ParticleEmitterDefClass::Load_W3D"]
    ParticleEmitterDefClass__Save_W3D["ParticleEmitterDefClass::Save_W3D"]
    ParticleEmitterLoaderClass__Load_W3D["ParticleEmitterLoaderClass::Load_W3D"]
    Partition["Partition"]
    PersistClass__Load["PersistClass::Load"]
    PersistClass__Save["PersistClass::Save"]
    PKey__Decode_Modulus_Decode_Exponent["PKey::Decode_Modulus/Decode_Exponent"]
    PKey__Decrypt["PKey::Decrypt"]
    PKey__Encode_Modulus_Encode_Exponent["PKey::Encode_Modulus/Encode_Exponent"]
    PKey__Encrypt["PKey::Encrypt"]
    PKey__Generate["PKey::Generate"]
    Play["Play"]
    Prepare_Directories["Prepare_Directories"]
    Preprocess_And_Assemble_Shader_From_File["Preprocess_And_Assemble_Shader_From_File"]
    Process__["Process()"]
    Process_Block["Process_Block"]
    Process_DD_Result["Process_DD_Result"]
    Process_Head["Process_Head"]
    Process_Reduction__["Process_Reduction()"]
    Profile__StartRange["Profile::StartRange"]
    Profile__StopRange["Profile::StopRange"]
    ProfileAllocMemory["ProfileAllocMemory"]
    ProfileFuncLevelTracer__Enter["ProfileFuncLevelTracer::Enter"]
    ProfileFuncLevelTracer__Leave["ProfileFuncLevelTracer::Leave"]
    ProfileGetTime["ProfileGetTime"]
    ProfileHighLevel__AddProfile["ProfileHighLevel::AddProfile"]
    ProfileHighLevel__Block___Block["ProfileHighLevel::Block::~Block"]
    ProfileHighLevel__Block__Block["ProfileHighLevel::Block::Block"]
    ProfileId__FrameEnd["ProfileId::FrameEnd"]
    ProfileId__FrameStart["ProfileId::FrameStart"]
    ProfileReAllocMemory["ProfileReAllocMemory"]
    Put_Key_Message["Put_Key_Message"]
    Put_Point_char_const__section__char_const__entry__TPoint2D_int__const___value_["Put_Point(char const  section, char const  entry, TPoint2D<int> const & value)"]
    Put_String_char_const__section__char_const__entry__char_const__value_["Put_String(char const  section, char const  entry, char const  value)"]
    RandomStraw__Seed_Byte["RandomStraw::Seed_Byte"]
    RandomStraw__Seed_Long["RandomStraw::Seed_Long"]
    RandomStraw__Seed_Short["RandomStraw::Seed_Short"]
    RawFileClass__Open["RawFileClass::Open"]
    RawFileClass__Read["RawFileClass::Read"]
    RawFileClass__Write["RawFileClass::Write"]
    Read["Read"]
    Read_B8G8R8A8["Read_B8G8R8A8"]
    read_channel["read_channel"]
    Read_Frame["Read_Frame"]
    read_header["read_header"]
    Read_Line__Straw__char_["Read_Line (Straw, char)"]
    Read_Line__Straw__wchar_t_["Read_Line (Straw, wchar_t)"]
    read_vertices["read_vertices"]
    recursion["recursion"]
    recursion2["recursion2"]
    recursionShell["recursionShell"]
    REF_about["REF_about"]
    Register_Factory_DefinitionFactoryClass_factory_["Register_Factory(DefinitionFactoryClass factory)"]
    Register_Factory_ShdDefFactoryClass_factory_["Register_Factory(ShdDefFactoryClass factory)"]
    RegistryClass__Delete_Registry_Tree["RegistryClass::Delete_Registry_Tree"]
    RegistryClass__Save_Registry["RegistryClass::Save_Registry"]
    Remove["Remove"]
    Render["Render"]
    Render_RenderInfoClass___rinfo_["Render(RenderInfoClass & rinfo)"]
    Render_Preprocessed_Triangle["Render_Preprocessed_Triangle"]
    Render_Seg_Line["Render_Seg_Line"]
    Render_Triangle_Strip["Render_Triangle_Strip"]
    Render_Triangles["Render_Triangles"]
    RenderDeviceDescClass__operator_["RenderDeviceDescClass::operator="]
    RenderObjPersistFactoryClass__Save["RenderObjPersistFactoryClass::Save"]
    RenderStreak["RenderStreak"]
    Report_Load_On_Demand_RObj["Report_Load_On_Demand_RObj"]
    Report_Load_On_Demand_RObj_Report_Load_On_Demand_HAnim_Report_Load_On_Demand_HTree["Report_Load_On_Demand_RObj/Report_Load_On_Demand_HAnim/Report_Load_On_Demand_HTree"]
    Report_Missing_RObj_Report_Missing_HAnim_Report_Missing_HTree["Report_Missing_RObj/Report_Missing_HAnim/Report_Missing_HTree"]
    Reset["Reset"]
    Resize["Resize"]
    Resume_Sample["Resume_Sample"]
    RGB565_To_ARGB8888["RGB565_To_ARGB8888"]
    RigidDecalMeshClass__Render["RigidDecalMeshClass::Render"]
    RingMeshClass__Generate["RingMeshClass::Generate"]
    RLE_Blit["RLE_Blit"]
    RLE_Blit__overload_1_["RLE_Blit (overload 1)"]
    RLE_Blit__overload_2_["RLE_Blit (overload 2)"]
    RLEEngine__Compress["RLEEngine::Compress"]
    Save["Save"]
    Save_Load["Save/Load"]
    Save_Shader_ChunkSaveClass__csave__ShdDefClass_shddef_["Save_Shader(ChunkSaveClass& csave, ShdDefClass shddef)"]
    Save_Texture["Save_Texture"]
    Save_Variables["Save_Variables"]
    Save_W3D["Save_W3D"]
    SaveLoadSystemClass__Load["SaveLoadSystemClass::Load"]
    SaveLoadSystemClass__Post_Load_Processing["SaveLoadSystemClass::Post_Load_Processing"]
    SaveLoadSystemClass__Register_Post_Load_Callback["SaveLoadSystemClass::Register_Post_Load_Callback"]
    SaveLoadSystemClass__Request_Pointer_Remap["SaveLoadSystemClass::Request_Pointer_Remap"]
    SaveLoadSystemClass__Save["SaveLoadSystemClass::Save"]
    SceneClass__Render["SceneClass::Render"]
    Seek["Seek"]
    Select_Splitting_Plane["Select_Splitting_Plane"]
    service_stream["service_stream"]
    Set_Animation["Set_Animation"]
    Set_Arrays["Set_Arrays"]
    Set_LocsWidthsColors["Set_LocsWidthsColors"]
    Set_Mapper["Set_Mapper"]
    Set_Material["Set_Material"]
    Set_Ortho_Projection["Set_Ortho_Projection"]
    Set_Palette["Set_Palette"]
    Set_Perspective_Projection["Set_Perspective_Projection"]
    Set_Remap["Set_Remap"]
    Set_Render_State["Set_Render_State"]
    Set_Sample_Loop_Count["Set_Sample_Loop_Count"]
    Set_Sample_MS_Position["Set_Sample_MS_Position"]
    Set_Sample_Pan["Set_Sample_Pan"]
    Set_Sample_Playback_Rate["Set_Sample_Playback_Rate"]
    Set_Sample_User_Data["Set_Sample_User_Data"]
    Set_Sample_Volume["Set_Sample_Volume"]
    Set_Shader["Set_Shader"]
    Set_Texture["Set_Texture"]
    Set_Texture_Reduction["Set_Texture_Reduction"]
    Set_Transform["Set_Transform"]
    Set_Video_Mode["Set_Video_Mode"]
    Setup_Mix_File["Setup_Mix_File"]
    Setup_Self_Shadow_Info["Setup_Self_Shadow_Info"]
    SHAEngine__Hash["SHAEngine::Hash"]
    SHAEngine__Process_Block["SHAEngine::Process_Block"]
    SHAPipe__Put["SHAPipe::Put"]
    SHAPipe__Result["SHAPipe::Result"]
    ShatterSystem__Shatter_Mesh["ShatterSystem::Shatter_Mesh"]
    ShdDefClass__Load["ShdDefClass::Load"]
    ShdDefClass__Load_Variables["ShdDefClass::Load_Variables"]
    ShdDefClass__Save["ShdDefClass::Save"]
    ShdDefClass__Save_Load["ShdDefClass::Save/Load"]
    ShdDefClass__Save_Variables["ShdDefClass::Save_Variables"]
    ShdHWShader__Preprocess_And_Assemble_Shader_From_File["ShdHWShader::Preprocess_And_Assemble_Shader_From_File"]
    ShdHWVertexShader__Create__file_version_["ShdHWVertexShader::Create (file version)"]
    ShdHWVertexShader__Create__file_name__declaration_["ShdHWVertexShader::Create (file_name, declaration)"]
    ShdHWVertexShader__Create__shader_code__declaration_["ShdHWVertexShader::Create (shader_code, declaration)"]
    ShdMeshClass__Load_W3D["ShdMeshClass::Load_W3D"]
    ShdMeshLegacyLoaderClass__Load_W3D["ShdMeshLegacyLoaderClass::Load_W3D"]
    ShdMeshLoaderClass__Load_W3D["ShdMeshLoaderClass::Load_W3D"]
    Shell_Run["Shell_Run"]
    Show_Mouse["Show_Mouse"]
    showResults["showResults"]
    Shutdown["Shutdown"]
    SimpleDynVecClass__Add["SimpleDynVecClass::Add"]
    SimpleDynVecClass__Delete["SimpleDynVecClass::Delete"]
    SimpleDynVecClass__Grow["SimpleDynVecClass::Grow"]
    SimpleDynVecClass__Shrink["SimpleDynVecClass::Shrink"]
    SimpleFileFactoryClass__Get_File["SimpleFileFactoryClass::Get_File"]
    SimpleSceneClass__Customized_Render["SimpleSceneClass::Customized_Render"]
    SimpleVecClass__Resize["SimpleVecClass::Resize"]
    Single_Anim_Progress["Single_Anim_Progress"]
    Size["Size"]
    SkinDecalMeshClass__Render["SkinDecalMeshClass::Render"]
    SLNode_T___Data["SLNode<T>::Data"]
    SLNode_T___Next["SLNode<T>::Next"]
    SnapPointsClass__Load_W3D["SnapPointsClass::Load_W3D"]
    Sort_Vertices["Sort_Vertices"]
    SoundBufferClass__Determine_Stats["SoundBufferClass::Determine_Stats"]
    SoundBufferClass__Load_From_File["SoundBufferClass::Load_From_File"]
    SoundBufferClass__Load_From_Memory["SoundBufferClass::Load_From_Memory"]
    SpecialRenderInfoClass_CameraClass____int_["SpecialRenderInfoClass(CameraClass &, int)"]
    SpherePrototypeClass__Load["SpherePrototypeClass::Load"]
    SphereRenderObjClass__Render["SphereRenderObjClass::Render"]
    StackAllocator__New["StackAllocator::New"]
    Start_Sample["Start_Sample"]
    STM_AccessAdvance["STM_AccessAdvance"]
    STM_AccessGetBlock["STM_AccessGetBlock"]
    STM_AccessUpdate["STM_AccessUpdate"]
    STM_StreamCreate["STM_StreamCreate"]
    STM_StreamDestroy["STM_StreamDestroy"]
    Stop["Stop"]
    Stop_Sample["Stop_Sample"]
    streamFill["streamFill"]
    strtok_r["strtok_r"]
    subdivision_util["subdivision_util"]
    Submit_Key["Submit_Key"]
    Submit_Vertex["Submit_Vertex"]
    SuperClassID_From_ClassID["SuperClassID_From_ClassID"]
    TextTextureClass_constructor_destructor["TextTextureClass constructor/destructor"]
    TimeCodedMotionChannelClass__Get_Vector["TimeCodedMotionChannelClass::Get_Vector"]
    To_ASCII["To_ASCII"]
    To_Buffer["To_Buffer"]
    TriClass__Contains_Point["TriClass::Contains_Point"]
    Uncompress_Data["Uncompress_Data"]
    Uninitialised_Grow["Uninitialised_Grow"]
    Unregister_Factory_DefinitionFactoryClass_factory_["Unregister_Factory(DefinitionFactoryClass factory)"]
    Unregister_Factory_ShdDefFactoryClass_factory_["Unregister_Factory(ShdDefFactoryClass factory)"]
    Update_Arc_List["Update_Arc_List"]
    Update_Arrays["Update_Arrays"]
    Update_Bounding_Boxes["Update_Bounding_Boxes"]
    Update_Bounding_Boxes_Recursive["Update_Bounding_Boxes_Recursive"]
    Update_Cached_Bounding_Volumes["Update_Cached_Bounding_Volumes"]
    Update_Culling["Update_Culling"]
    Update_Kinematic_Particle_State__["Update_Kinematic_Particle_State()"]
    Update_Obj_Space_Bounding_Volumes["Update_Obj_Space_Bounding_Volumes"]
    Update_Sub_Object_Transforms["Update_Sub_Object_Transforms"]
    Update_Texture_Flash__["Update_Texture_Flash()"]
    Update_WS_Bounding_Volume["Update_WS_Bounding_Volume"]
    Validate_Active_Ref["Validate_Active_Ref"]
    Validate_Texture["Validate_Texture"]
    Vector4_to_Color["Vector4_to_Color"]
    VectorClass_T___Resize["VectorClass<T>::Resize"]
    VehicleCurveClass__Save___Load["VehicleCurveClass::Save / Load"]
    WideStringClass__Format["WideStringClass::Format"]
    Windows_Message_Handler["Windows_Message_Handler"]
    WindowsDebugPrint["WindowsDebugPrint"]
    Write["Write"]
    Write_B8G8R8A8["Write_B8G8R8A8"]
    WWDebug_Check_Trigger["WWDebug_Check_Trigger"]
    WWDebug_Printf["WWDebug_Printf"]
    WWDebug_Printf_Error["WWDebug_Printf_Error"]
    WWDebug_Printf_Warning["WWDebug_Printf_Warning"]
    WWDebug_Profile_Start["WWDebug_Profile_Start"]
    WWDebug_Profile_Stop["WWDebug_Profile_Stop"]
    WWKeyboardClass__Message_Handler["WWKeyboardClass::Message_Handler"]
    WWKeyboardClass__Put_Key_Message["WWKeyboardClass::Put_Key_Message"]
    WWKeyboardClass__Put_Mouse_Message["WWKeyboardClass::Put_Mouse_Message"]
    WWMemoryAndTimeLog__Log_Intermediate["WWMemoryAndTimeLog::Log_Intermediate"]
    WWMemoryLogClass__Allocate_Memory["WWMemoryLogClass::Allocate_Memory"]
    WWMemoryLogClass__Release_Memory["WWMemoryLogClass::Release_Memory"]
    WWMouseClass__Capture_Mouse["WWMouseClass::Capture_Mouse"]
    WWMouseClass__Process_Mouse["WWMouseClass::Process_Mouse"]
    WWMouseClass__Release_Mouse["WWMouseClass::Release_Mouse"]
    WWMouseClass__Set_Cursor["WWMouseClass::Set_Cursor"]
    WWProfile_Get_Ticks["WWProfile_Get_Ticks"]
    WWProfileHierachyNodeClass__Call["WWProfileHierachyNodeClass::Call"]
    WWProfileHierachyNodeClass__Return["WWProfileHierachyNodeClass::Return"]
    WWProfileManager__Start_Profile["WWProfileManager::Start_Profile"]
    WWProfileManager__Stop_Profile["WWProfileManager::Stop_Profile"]
    XMP_Exponent_Mod["XMP_Exponent_Mod"]
    XMP_Is_Prime["XMP_Is_Prime"]
    XMP_Mult["XMP_Mult"]
    XMP_Rabin_Miller_Test["XMP_Rabin_Miller_Test"]
    XSurface__Blit_From["XSurface::Blit_From"]
    XSurface__Blit_Plain["XSurface::Blit_Plain"]
    XSurface__Blit_Trans["XSurface::Blit_Trans"]
    XSurface__Draw_Line["XSurface::Draw_Line"]
    XSurface__Fill_Rect["XSurface::Fill_Rect"]
  end

  getCompressionType --> memcmp
  BTREE_about --> galloc
  BTREE_about --> memset
  BTREE_about --> strcpy
  HUFF_about --> galloc
  HUFF_about --> memset
  HUFF_about --> strcpy
  REF_about --> galloc
  REF_about --> memset
  REF_about --> strcpy
  ProfileAllocMemory --> GlobalAlloc
  ProfileReAllocMemory --> GlobalAlloc
  ProfileReAllocMemory --> GlobalFree
  ProfileReAllocMemory --> memcpy
  GetClockCyclesFast --> timeGetTime
  GetClockCyclesFast --> QueryPerformanceCounter
  GetClockCyclesFast --> QueryPerformanceFrequency
  GetClockCyclesFast --> ProfileGetTime
  Profile__StartRange --> ProfileReAllocMemory
  Profile__StartRange --> ProfileAllocMemory
  Profile__StopRange --> ProfileReAllocMemory
  Profile__StopRange --> ProfileAllocMemory
  AddResultFunction --> ProfileReAllocMemory
  Execute --> ProfileAllocMemory
  _penter --> TlsGetValue
  _penter --> ProfileAllocMemory
  _pleave --> TlsGetValue
  ProfileFuncLevelTracer__Enter --> ProfileGetTime
  ProfileFuncLevelTracer__Enter --> ProfileAllocMemory
  ProfileFuncLevelTracer__Leave --> ProfileGetTime
  ProfileHighLevel__AddProfile --> ProfileAllocMemory
  ProfileHighLevel__AddProfile --> new
  ProfileHighLevel__Block__Block --> ProfileGetTime
  ProfileHighLevel__Block___Block --> ProfileGetTime
  ProfileId__FrameStart --> ProfileAllocMemory
  ProfileId__FrameStart --> ProfileReAllocMemory
  ProfileId__FrameEnd --> ProfileReAllocMemory
  calcThat --> calcThis
  recursion --> recursion2
  recursion2 --> recursion
  recursionShell --> recursion
  main --> calcThis
  main --> calcThat
  main --> recursionShell
  main --> showResults
  audioChannelCreate --> AudioAttribsInit
  AudioChannelStart --> audioChannelRecalcAttribs
  audioChannelRecalcAttribs --> AudioAttribsInit
  STM_AccessUpdate --> STM_next_sbuffer
  STM_AccessAdvance --> STM_next_sbuffer
  STM_AccessAdvance --> STM_AccessUpdate
  STM_AccessGetBlock --> STM_AccessAdvance
  AudioStreamerInit --> AUD_ThreadCreate
  service_stream --> streamFill
  highResGetTime --> QueryPerformanceCounter
  failsafeGetTime --> timeGetTime
  InitAudioTimer --> QueryPerformanceFrequency
  AUD_ThreadCreate --> CreateThread
  AUD_ThreadDestroy --> WaitForSingleObject
  AUD_ThreadDestroy --> CloseHandle
  Update_Bounding_Boxes_Recursive --> Update_Min_Max
  Cast_Ray --> Cast_Ray_Recursive
  Update_Bounding_Boxes --> Update_Bounding_Boxes_Recursive
  Build_AABTree --> Reset
  Build_AABTree --> Build_Tree
  Build_AABTree --> Compute_Bounding_Box
  Build_AABTree --> Assign_Index
  Build_Tree --> Select_Splitting_Plane
  Build_Tree --> Split_Polys
  Build_Tree --> Compute_Bounding_Box
  Select_Splitting_Plane --> Compute_Plane_Score
  Select_Splitting_Plane --> Which_Side
  Build_AABTree --> Export
  Build_Tree --> Assign_Index
  Compute_Plane_Score --> Which_Side
  Compute_Plane_Score --> Update_Min_Max
  Render --> Single_Anim_Progress
  Render --> Update_Sub_Object_Transforms
  Set_Animation --> Release
  Set_Animation --> Add_Ref
  Update_Sub_Object_Transforms --> Base_Update
  Update_Sub_Object_Transforms --> Anim_Update
  Update_Sub_Object_Transforms --> Blend_Update
  Update_Sub_Object_Transforms --> Combo_Update
  Report_Load_On_Demand_RObj_Report_Load_On_Demand_HAnim_Report_Load_On_Demand_HTree --> Add_To_Report
  Report_Missing_RObj_Report_Missing_HAnim_Report_Missing_HTree --> Add_To_Report
  Report_Load_On_Demand_RObj --> Add_To_Report
  Bitmap_Assert --> WWASSERT
  Create_Mipmap_B8G8R8A8 --> Combine_A8R8G8B8
  Copy_Image_Generate_Mipmap --> Combine_A8R8G8B8
  Copy_Image_Generate_Mipmap --> Recolor
  Copy_Image_Generate_Mipmap --> Read_B8G8R8A8
  Copy_Image_Generate_Mipmap --> Write_B8G8R8A8
  Copy_Image --> Get_Bytes_Per_Pixel
  Copy_Image --> Read_B8G8R8A8
  Copy_Image --> Write_B8G8R8A8
  Copy_Image --> Recolor
  Copy_Image --> Copy_Pixel
  Read_B8G8R8A8 --> Bitmap_Assert
  Read_B8G8R8A8 --> Get_Bytes_Per_Pixel
  Write_B8G8R8A8 --> Bitmap_Assert
  Copy_Pixel --> Read_B8G8R8A8
  Copy_Pixel --> Write_B8G8R8A8
  Copy_Pixel --> Recolor
  Copy_Image_Generate_Mipmap --> Copy_Pixel
  Copy_Image_Generate_Mipmap --> Create_Mipmap_B8G8R8A8
  Copy_Image --> Copy_Image_Generate_Mipmap
  Bitmap2DObjClass__filename_constructor_ --> DynamicScreenMeshClass
  Bitmap2DObjClass__texture_constructor_ --> DynamicScreenMeshClass
  Bitmap2DObjClass__copy_constructor_ --> DynamicScreenMeshClass
  BoxRenderObjClass__Init --> NEW_REF
  BoxRenderObjClass__render_box --> DX8Wrapper
  Render_Triangle_Strip --> Cull
  Render_Triangle_Strip --> Render_Preprocessed_Triangle
  Render_Triangles --> Cull
  Render_Triangles --> Render_Preprocessed_Triangle
  BWRenderClass__Render_Triangles --> Render_Preprocessed_Triangle
  BWRenderClass__Render_Triangle_Strip --> Render_Preprocessed_Triangle
  Update_Obj_Space_Bounding_Volumes --> Get_Obj_Space_Bounding_Sphere
  Update_Obj_Space_Bounding_Volumes --> Get_Obj_Space_Bounding_Box
  Get_Pixel --> RGB565_To_ARGB8888
  Get_Pixel --> Combine_Colors
  Get_4x4_Block --> RGB565_To_ARGB8888
  Get_4x4_Block --> Combine_Colors
  Get_4x4_Block --> Recolor
  DecalPolyClass__Clip --> Reset
  RigidDecalMeshClass__Render --> Process_Material_Run
  SkinDecalMeshClass__Render --> Process_Material_Run
  DecalSystemClass__Lock_Decal_Generator --> W3DNEW
  DecalSystemClass__Lock_Decal_Generator --> Generate_Decal_Id
  MultiFixedPoolDecalSystemClass__Unlock_Decal_Generator --> find_logical_decal
  MultiFixedPoolDecalSystemClass__Clear_Decal_Slot --> find_logical_decal
  MultiFixedPoolDecalSystemClass__Lock_Decal_Generator --> Generate_Decal_Id
  Check_Driver_Version_Status --> stricmp
  Log --> WWDEBUG_SAY
  Shutdown --> delete
  Remove --> delete
  Set_Texture --> REF_PTR_SET
  HCompressedAnimClass__Load_W3D --> read_channel
  HCompressedAnimClass__Load_W3D --> read_bit_channel
  HCompressedAnimClass__Load_W3D --> add_channel
  HCompressedAnimClass__Load_W3D --> add_bit_channel
  Load_W3D --> read_header
  HRawAnimClass__Load_W3D --> Free
  HRawAnimClass__Load_W3D --> read_channel
  HRawAnimClass__Load_W3D --> add_channel
  HRawAnimClass__Load_W3D --> read_bit_channel
  HRawAnimClass__Load_W3D --> add_bit_channel
  HRawAnimClass__Get_Orientation --> Fast_Slerp
  HRawAnimClass__Get_Transform --> Fast_Slerp

